### ISSUE TITLE
can't find this project in cocoapods

### ISSUE THREAD

**Issue by saber1024** [Augustyniak/FileExplorer#21]
i try 

> Saber@SaberdeMacBook-Pro BLEPROJECT$ pod search FileExplorer
[!] Unable to find a pod with name, author, summary, or description matching `FileExplorer`

and
target :BLEPROJECT do
 pod "FileExplorer", "~> 1.0.4"
end

still can't find this project

**Comment by Augustyniak** [comment]
Hi @saber1024,

Thanks for reporting it! 👍 I think that your instance of CocoaPods uses an outdated version of master repo. You can update that repo by running command `pod repo update`. It should allow you to use the newest version of FileExplorer.

Please let me know if it solves your problem!
