### ISSUE TITLE
Change iOS Deployment Target to lower SDK levels

### ISSUE THREAD

**Issue by andrewcl** [Augustyniak/FileExplorer#8]
Are there any iOS 10.0 specific API's being used by this library? Would it be possible to lower the deployment target so that legacy projects could make use of this library?

**Comment by Augustyniak** [comment]
Thanks for the idea! 👍

You're right. I think that iOS 9 is totally possible (although I'm not sure). `FileExplorer` uses anchors which were introduced in iOS 9 so we won't get lower than 9. I think that support for two last major versions of the system, iOS 9 and iOS 10, would be great.

**Comment by andrewcl** [comment]
Supporting the previous and current iOS version is the best approach since the percentage of devices supporting way back iOS versions is small.

I tested dropping the minimum deployment target for FileExplorer to 9.0 in my own 9.0 project and I'm not seeing any issues so far. Thanks for the prompt response and for releasing this library!

**Comment by Augustyniak** [comment]
> Supporting the previous and current iOS version is the best approach since the percentage of devices supporting way back iOS versions is small.

Totally agree. 👍

Version [v1.0.3](https://github.com/Augustyniak/FileExplorer/releases/tag/v1.0.3) requires at least 9.0 (not 10.0). 🎉 

@andrewcl Thanks one more time! I'm closing this issue. Feel free to reopen if necessary.
